sudo: required

services:
  -maven

script:
 - maven run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/maven-asciidoctor asciidoctor -D 
 /documents/output *.adoc      
  - maven run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/maven-asciidoctor asciidoctor-pdf -D 
  /documents/output *.adoc 
  
  after_error: 
  - maven logs asciidoc-to-html
  - maven logs asciidoc-to-pdf
  
  after_success:      
  - cd output ; mv README.html index.html ; cp -R ../images images
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
